const express=require('express')
const router=express.Router()
const isAdmin=require('../middlewares/isAdmin')
const authenticate=require('../middlewares/authMiddleware')
const { allUsers, singleUsers, userBlock, totalRevenue, AllOrders, getUserOrder } = require('../controllers/adminController')
const { addProduct, deleteProduct, updateProduct, getallProducts, singleProduct } = require('../controllers/productController')
const { getTotalPurchased } = require('../controllers/adminController')
const upload=require('../middlewares/uploadMiddleware')
const uploadCloudinary=require('../middlewares/uploadCloudinary')

router.get('/getusers',authenticate,isAdmin,allUsers)
router.get('/getusers/:id',authenticate,isAdmin,singleUsers)
router.patch('/blockUser/:id',authenticate,isAdmin,userBlock)
router.get('/getProducts',authenticate,isAdmin,getallProducts)
router.get('/getProducts/:id',authenticate,isAdmin,singleProduct)
router.post('/addProduct',authenticate,isAdmin,upload.single('url'),uploadCloudinary,addProduct)
router.delete('/deleteProduct/:productId',authenticate,isAdmin,deleteProduct)
router.put('/updateProduct/:id',authenticate,isAdmin,upload.single('url'),updateProduct)
router.get('/totalPurchased',authenticate,isAdmin,getTotalPurchased)
router.get('/totalRevenue',authenticate,isAdmin,totalRevenue)
// router.get('/allOrders',authenticate,isAdmin,AllOrders)
router.get('/getUserOrder/:id',authenticate,isAdmin,getUserOrder)

module.exports=router